### ISSUE TITLE
Add an email field/subscription button to add to mailing list

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#15] opened 2017-03-26 20:37 UTC
Aside from the contact form, users should be able to add their email to our mailing list once we get that set up

**Comment by mokolabs** [comment] 2017-03-27 18:33
Ooops. I made a duplicate of this issue. Sorry!

But I'm going to close this one anyway, since my version includes the sub tasks we need to do for this.

**Closed as completed by mokolabs** 2017-03-27 18:33 UTC
